// This file is generated by Velite

import type __vc from '../velite.config.ts'

type Collections = typeof __vc.collections

export type Post = Collections['posts']['schema']['_output']
export declare const posts: Post[]

export type Portofolio = Collections['portofolio']['schema']['_output']
export declare const portofolio: Portofolio[]
